# Generated by Django 6.1.1 on 2026-09-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passoword',
        ),
        migrations.AddField(
            model_name='user',
            name='is_current_user',
            field=models.BooleanField(default=0),
        ),
    ]
